[package]
name = "opencv1"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = "0.95.1"



[dev-dependencies.matches]
version = "0.1"

[features]
rgb = []
cudaimgproc = []
opencv_branch_4 = []